# This workflow will run fairtally on the RSD data once an hour and push the results to the repo
#
# TODO:
#    - push result to repo
#    - generate an overview from the report and automatically create an issue out of that?
#    - set frequency to daily or weekly and move to TL repo?

name: RSDHarvest

on:  
  schedule:   
    - cron: "0 3 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  fairtally:

    runs-on: ubuntu-latest

  steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - run: ./gradlew build --no-daemon

