# This is a automated harvester
name: RSDHarvester

on:  
  schedule:   
    - cron: "0 3 * * *"

  workflow_dispatch:

permissions:
  contents: read

jobs:
  harvest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build harvester
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'gradle'
    - name: Build harvester
      run: ./gradlew build --no-daemon  
    - name: Run harvester
      run: /bin/bash run-harvester.sh 
    - name: Commit results
      run: | 
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add data
        git commit -m "Add harvested data" -a
           
#    - name: Push changes
#      uses: ad-m/github-push-action@master
#      with:
#        github_token: ${{ secrets.GITHUB_TOKEN }}
