# This is a automated harvester
name: RSDHarvester

on:  
  schedule:   
    - cron: "0 3 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  harvest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build harvester
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'gradle'
    - name: Build harvester
      run: ./gradlew build --no-daemon  
    - name: Copy libs
      run: ./gradlew copyRuntimeLibs --no-daemon  
    - name: Run harvester
      run: /bin/bash run-harvester.sh 
    - name: Cleanup
      run: ./gradlew clean --no-daemon  
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: 'data/*'
      
